-- Find total customers by countries 
SELECT 
	Country,
	COUNT(*) Total_Customers
FROM gold.dim_customers
GROUP BY country 
ORDER BY 2 DESC

-- Find  total customers by Gender

SELECT 
	gender,
	COUNT(*) Total_Customers
FROM gold.dim_customers
GROUP BY gender 
ORDER BY 2 DESC	

-- Find the total products by category 

SELECT 
	category,
	COUNT(*) Total_Products
FROM gold.dim_products
GROUP BY category
ORDER BY 2 DESC	

-- What is the average costs in each category 

SELECT 
	category,
	AVG(cost) AS Average_costs
FROM gold.dim_products
GROUP BY category
ORDER BY 2 DESC	

-- What is the average sales in each category 

SELECT 
	p.category,
	AVG(sales_amount) AS average_Sales
FROM gold.dim_products p
INNER JOIN 
gold.fact_sales f
ON p.product_key = f.product_key
GROUP BY p.category;

-- what  is the total revenue generate for each category

SELECT 
	p.category,
	SUM(sales_amount) AS total_revenue
FROM gold.dim_products p
INNER JOIN 
gold.fact_sales f
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- What is the total revenue generated by each customer ?

SELECT 
	f.customer_key,
	c.first_name,
	c.last_name,
	SUM(sales_amount) AS total_revenue
FROM gold.dim_customers c
LEFT JOIN 
gold.fact_sales f
ON f.customer_key = c.customer_key
GROUP BY 
	f.customer_key,
	c.first_name,
	c.last_name
ORDER BY total_revenue DESC

-- What is the disstributions of items sold across countries ?
-- OR , Total quantity of items sold acorss countires 

SELECT 
	c.country,
	SUM(quantity) AS total_sold_items
FROM gold.dim_customers c
LEFT JOIN 
gold.fact_sales f
ON f.customer_key = c.customer_key
GROUP BY 
	c.country
ORDER BY total_sold_items DESC